# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Member.create(:name => '秋元 真夏',:team => '乃木坂46',:generation => 1)
Member.create(:name => '生田 絵梨花',:team => '乃木坂46',:generation => 1)
Member.create(:name => '齋藤 飛鳥',:team => '乃木坂46',:generation => 1)
Member.create(:name => '白石 麻衣',:team => '乃木坂46',:generation => 1)
Member.create(:name => '高山 一実',:team => '乃木坂46',:generation => 1)
Member.create(:name => '中田 花奈',:team => '乃木坂46',:generation => 1)
Member.create(:name => '樋口 日奈',:team => '乃木坂46',:generation => 1)
Member.create(:name => '星野 みなみ',:team => '乃木坂46',:generation => 1)
Member.create(:name => '松村 沙友理',:team => '乃木坂46',:generation => 1)
Member.create(:name => '和田 まあや',:team => '乃木坂46',:generation => 1)
Member.create(:name => '伊藤 純奈',:team => '乃木坂46',:generation => 2)
Member.create(:name => '北野 日奈子',:team => '乃木坂46',:generation => 2)
Member.create(:name => '新内 眞衣',:team => '乃木坂46',:generation => 2)
Member.create(:name => '鈴木 絢音',:team => '乃木坂46',:generation => 2)
Member.create(:name => '寺田 蘭世',:team => '乃木坂46',:generation => 2)
Member.create(:name => '堀未 央奈',:team => '乃木坂46',:generation => 2)
Member.create(:name => '山崎 怜奈',:team => '乃木坂46',:generation => 2)
Member.create(:name => '渡辺 みり愛',:team => '乃木坂46',:generation => 2)
Member.create(:name => '伊藤 理々杏',:team => '乃木坂46',:generation => 3)
Member.create(:name => '岩本 蓮加',:team => '乃木坂46',:generation => 3)
Member.create(:name => '梅澤 美波',:team => '乃木坂46',:generation => 3)
Member.create(:name => '大園 桃子',:team => '乃木坂46',:generation => 3)
Member.create(:name => '久保 史緒里',:team => '乃木坂46',:generation => 3)
Member.create(:name => '阪口 珠美',:team => '乃木坂46',:generation => 3)
Member.create(:name => '佐藤 楓',:team => '乃木坂46',:generation => 3)
Member.create(:name => '中村 麗乃',:team => '乃木坂46',:generation => 3)
Member.create(:name => '向井 葉月',:team => '乃木坂46',:generation => 3)
Member.create(:name => '山下 美月',:team => '乃木坂46',:generation => 3)
Member.create(:name => '吉田 綾乃',:team => '乃木坂46',:generation => 3)
Member.create(:name => '与田 祐希',:team => '乃木坂46',:generation => 3)
Member.create(:name => '遠藤 さくら',:team => '乃木坂46',:generation => 4)
Member.create(:name => '賀喜 遥香',:team => '乃木坂46',:generation => 4)
Member.create(:name => '掛橋 沙耶香',:team => '乃木坂46',:generation => 4)
Member.create(:name => '金川 紗耶',:team => '乃木坂46',:generation => 4)
Member.create(:name => '北川 悠理',:team => '乃木坂46',:generation => 4)
Member.create(:name => '黒見 明香',:team => '乃木坂46',:generation => 4)
Member.create(:name => '佐藤 璃果',:team => '乃木坂46',:generation => 4)
Member.create(:name => '柴田 柚菜',:team => '乃木坂46',:generation => 4)
Member.create(:name => '清宮 レイ',:team => '乃木坂46',:generation => 4)
Member.create(:name => '田村 真佑',:team => '乃木坂46',:generation => 4)
Member.create(:name => '筒井 あやめ',:team => '乃木坂46',:generation => 4)
Member.create(:name => '早川 聖来',:team => '乃木坂46',:generation => 4)
Member.create(:name => '林 瑠奈',:team => '乃木坂46',:generation => 4)
Member.create(:name => '松尾 美佑',:team => '乃木坂46',:generation => 4)
Member.create(:name => '矢久保 美緒',:team => '乃木坂46',:generation => 4)
Member.create(:name => '弓木 奈於',:team => '乃木坂46',:generation => 4)


Member.create(:name => '石森 虹花',:team => '欅坂46',:generation => 1)
Member.create(:name => '上村 莉菜',:team => '欅坂46',:generation => 1)
Member.create(:name => '尾関 梨香',:team => '欅坂46',:generation => 1)
Member.create(:name => '小池 美波',:team => '欅坂46',:generation => 1)
Member.create(:name => '小林 由依',:team => '欅坂46',:generation => 1)
Member.create(:name => '齋藤 冬優花',:team => '欅坂46',:generation => 1)
Member.create(:name => '佐藤 詩織',:team => '欅坂46',:generation => 1)
Member.create(:name => '菅井 友香',:team => '欅坂46',:generation => 1)
Member.create(:name => '土生 瑞穂',:team => '欅坂46',:generation =>  1)
Member.create(:name => '原田 葵',:team => '欅坂46',:generation => 1)
Member.create(:name => '守屋 茜',:team => '欅坂46',:generation => 1)
Member.create(:name => '渡辺 梨加',:team => '欅坂46',:generation => 1)
Member.create(:name => '渡邉 理佐',:team => '欅坂46',:generation => 1)
Member.create(:name => '井上 梨名',:team => '欅坂46',:generation => 2)
Member.create(:name => '遠藤 光莉',:team => '欅坂46',:generation => 2)
Member.create(:name => '大園 玲',:team => '欅坂46',:generation => 2)
Member.create(:name => '大沼 晶保',:team => '欅坂46',:generation => 2)
Member.create(:name => '幸阪 茉里乃',:team => '欅坂46',:generation => 2)
Member.create(:name => '関 有美子',:team => '欅坂46',:generation =>  2)
Member.create(:name => '武元 唯衣',:team => '欅坂46',:generation => 2)
Member.create(:name => '田村 保乃',:team => '欅坂46',:generation => 2)
Member.create(:name => '藤吉 夏鈴',:team => '欅坂46',:generation => 2)
Member.create(:name => '増本 綺良',:team => '欅坂46',:generation => 2)
Member.create(:name => '松田 里奈',:team => '欅坂46',:generation => 2)
Member.create(:name => '松平 璃子',:team => '欅坂46',:generation => 2)
Member.create(:name => '森田 ひかる',:team => '欅坂46',:generation => 2)
Member.create(:name => '守屋 麗奈',:team => '欅坂46',:generation => 2)
Member.create(:name => '山﨑 天',:team => '欅坂46',:generation => 2)


Member.create(:name => '潮紗 理菜',:team => '日向坂46',:generation => 1)
Member.create(:name => '影山 優佳',:team => '日向坂46',:generation => 1)
Member.create(:name => '加藤 史帆',:team => '日向坂46',:generation => 1)
Member.create(:name => '齊藤 京子',:team => '日向坂46',:generation => 1)
Member.create(:name => '佐々木 久美',:team => '日向坂46',:generation => 1)
Member.create(:name => '佐々木 美玲',:team => '日向坂46',:generation => 1)
Member.create(:name => '高瀬 愛奈',:team => '日向坂46',:generation => 1)
Member.create(:name => '高本 彩花',:team => '日向坂46',:generation => 1)
Member.create(:name => '東村 芽依',:team => '日向坂46',:generation => 1)
Member.create(:name => '金村 美玖',:team => '日向坂46',:generation => 2)
Member.create(:name => '河田 陽菜',:team => '日向坂46',:generation => 2)
Member.create(:name => '小坂 菜緒',:team => '日向坂46',:generation => 2)
Member.create(:name => '富田 鈴花',:team => '日向坂46',:generation => 2)
Member.create(:name => '丹生 明里',:team => '日向坂46',:generation => 2)
Member.create(:name => '濱岸 ひより',:team => '日向坂46',:generation => 2)
Member.create(:name => '松田 好花',:team => '日向坂46',:generation => 2)
Member.create(:name => '宮田 愛萌',:team => '日向坂46',:generation => 2)
Member.create(:name => '渡邉 美穂',:team => '日向坂46',:generation => 2)
Member.create(:name => '上村 ひなの',:team => '日向坂46',:generation => 3)
Member.create(:name => '髙橋 未来虹',:team => '日向坂46',:generation => 3)
Member.create(:name => '森本 茉莉',:team => '日向坂46',:generation => 3)
Member.create(:name => '山口 陽世',:team => '日向坂46',:generation => 3)


